baseURL = "https://affiliate-blog.netlify.app/"
languageCode = "en-us"
title = "Smart Gear Reviews"
theme = "your-theme-name"

[params]
  description = "Expert reviews, guides, and top picks for outdoor gear, power stations, and smart home essentials — helping you choose the best products faster."
