baseURL = "https://affiliate-blog.netlify.app/"
languageCode = "en-us"
title = "Smart Gear Reviews"
theme = "hermit"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
