[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.149.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "http://*"
  to = "https://affiliate-blog.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.affiliate-blog.netlify.app/*"
  to = "https://affiliate-blog.netlify.app/:splat"
  status = 301
  force = true

